version: '1.0'
services:
  eureka-server:
    build: eurekaServer/
    mem_limit: 512m
    ports:
      - "8761:8761"
  config-server:
    build: configServer/
    mem_limit: 512m
    ports:
      - "8888:8888"
  gateway:
    build: gateway/
    mem_limit: 512m
    ports:
      - "9090:9090"
  registration-user-service:
    build: registrationUserService/
    mem_limit: 512m
    ports:
      - "8081:8080"
  user-service:
    build: userService/
    mem_limit: 512m
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      start-dev