version: '1.0'
services:
  eureka-server:
    build: eurekaServer/
    mem_limit: 512m
    ports:
      - "8761:8761"
  config-server:
    build: configServer/
    mem_limit: 512m
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
  gateway:
    build: gateway/
    mem_limit: 512m
    ports:
      - "9090:9090"
    depends_on:
      - config-server
      - eureka-server
  registration-user-service:
    build: registrationUserService/
    mem_limit: 512m
    ports:
      - "8081:8080"
    depends_on:
      - keycloak
      - config-server
      - eureka-server
  user-service:
    build: userService/
    mem_limit: 512m
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db
      - config-server
      - eureka-server
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  keycloak:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin