spring:
  application:
    name: gateway
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/digital-money-house
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: userService
          uri: http://localhost:8082
          predicates:
            - Path=/users
server:
  port: 9090